[package]
name = "profiler"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
anyhow = "1"
blazesym = { version = "0.2.2", features = ["tracing"] }
clap = { version = "4.5", features = ["derive"] }
libbpf-rs = "0.24"
libc = "0.2"
nix = { version = "0.29", features = ["fs", "process"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "ansi"] }

[build-dependencies]
libbpf-cargo = "0.24"
